version: "3.11"

services:
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/ldubgd.nginx.conf:/etc/nginx/conf.d/default.conf
  #     - /opt/cert:/etc/ssl/cert
  #   depends_on:
  #     - backend
  #   restart: always

  backend:
    build:
      context: .
      dockerfile: ./backend/dockerfiles/dockerfile-backend
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - /opt/cert:/etc/ssl/cert
    environment:
      DB_CONNECTION_STRING: postgresql://postgres:postgres@database:5432/postgres?sslmode=allow
    restart: always

    depends_on:
      database:
        condition: service_healthy

    command: /bin/sh -c "alembic upgrade head && uvicorn proshield.main:app --reload --workers 1 --host 0.0.0.0 --port 8000 --ssl-keyfile /etc/ssl/cert/localhost.key --ssl-certfile /etc/ssl/cert/localhost.crt"

  database:
    image: postgres:16.6
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    command: postgres -c listen_addresses=0.0.0.0
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
