version: "3.11"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/dockerfiles/dockerfile-backend
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION_STRING: postgresql://postgres:postgres@database:5432/postgres?sslmode=allow
    restart: always

    depends_on:
      database:
        condition: service_healthy

    volumes:
      - ./backend:/app

    command: /bin/sh -c "alembic upgrade head && uvicorn proshield.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"

  database:
    image: postgres:16.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - proshield-data:/var/lib/postgresql/data
    command: postgres -c listen_addresses=0.0.0.0
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  proshield-data:
