version: '3.11'

services:
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/dockerfile-backend
    ports:
      - "8000:8000"
    volumes:
      - ./alembic.ini:/app/alembic.ini
      - .:/app
    environment:
      - ENVIRONMENT=DEV
    restart: always
    
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - type: volume
        target: /var/lib/postgresql/data
    command: postgres -c listen_addresses=0.0.0.0
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5