"""building types

Revision ID: 0736ea225068
Revises: c7c6b63c2052
Create Date: 2025-01-16 21:28:27.728513

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0736ea225068"
down_revision: Union[str, None] = "c7c6b63c2052"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "building_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_building_types")),
        sa.UniqueConstraint("name", name=op.f("uq_building_types_name")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("building_types")
    # ### end Alembic commands ###
