"""buildings coefficients

Revision ID: 08ab191091ba
Revises: 8b0cb1542719
Create Date: 2025-01-17 00:00:21.589815

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "08ab191091ba"
down_revision: Union[str, None] = "8b0cb1542719"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "building_coefficients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wall_material_id", sa.Integer(), nullable=False),
        sa.Column("building_type_id", sa.Integer(), nullable=False),
        sa.Column("wall_thickness", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("area_relation_percent", sa.Integer(), nullable=False),
        sa.Column("coefficient", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["building_type_id"],
            ["building_types.id"],
            name=op.f("fk_building_coefficients_building_type_id_building_types"),
        ),
        sa.ForeignKeyConstraint(
            ["wall_material_id"],
            ["wall_materials.id"],
            name=op.f("fk_building_coefficients_wall_material_id_wall_materials"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_building_coefficients")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("building_coefficients")
    # ### end Alembic commands ###
