"""location_condition_coefficients update

Revision ID: 1935e3f654a1
Revises: 08ab191091ba
Create Date: 2025-03-03 16:46:02.293979

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1935e3f654a1"
down_revision: Union[str, None] = "08ab191091ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "location_condition_coefficients",
        sa.Column("building_height", sa.String(), nullable=True),
    )

    op.execute(
        """
        UPDATE location_condition_coefficients
        SET building_height = '>=12'
        WHERE building_height_from = 12 AND building_height_to IS NULL
    """
    )

    op.execute(
        """
        UPDATE location_condition_coefficients
        SET building_height = '8-12'
        WHERE building_height_from = 8 AND building_height_to = 12
    """
    )

    op.execute(
        """
        UPDATE location_condition_coefficients
        SET building_height = '>=30'
        WHERE building_height_from = 30 AND building_height_to IS NULL
    """
    )

    op.execute(
        """
        UPDATE location_condition_coefficients
        SET building_height = '10-30'
        WHERE building_height_from = 10 AND building_height_to = 29
    """
    )

    op.execute(
        """
        UPDATE location_condition_coefficients
        SET building_height = '8-10'
        WHERE building_height_from = 8 AND building_height_to = 9
    """
    )

    op.drop_column("location_condition_coefficients", "building_height_from")
    op.drop_column("location_condition_coefficients", "building_height_to")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "location_condition_coefficients",
        sa.Column(
            "building_height_to", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "location_condition_coefficients",
        sa.Column(
            "building_height_from", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("location_condition_coefficients", "building_height")
    # ### end Alembic commands ###
