"""storage classes

Revision ID: 2816a14240cd
Revises: 
Create Date: 2025-01-14 15:21:01.170868

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2816a14240cd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_classes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("protection_class", sa.String(), nullable=False),
        sa.Column("overpressure_air_blast_wave", sa.Integer(), nullable=False),
        sa.Column("radiation_protection_level", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_storage_classes")),
        sa.UniqueConstraint(
            "protection_class", name=op.f("uq_storage_classes_protection_class")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("storage_classes")
    # ### end Alembic commands ###
