"""sub-materials

Revision ID: 6c0267128ac9
Revises: 1935e3f654a1
Create Date: 2025-04-24 06:09:56.982951

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c0267128ac9"
down_revision: Union[str, None] = "1935e3f654a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sub_materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_sub_materials_material_id_materials"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sub_materials")),
        sa.UniqueConstraint("name", name=op.f("uq_sub_materials_name")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sub_materials")
    # ### end Alembic commands ###
