"""sub-materials density

Revision ID: 9a7e1393479c
Revises: 6c0267128ac9
Create Date: 2025-04-24 06:36:08.998453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7e1393479c'
down_revision: Union[str, None] = '6c0267128ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_materials', sa.Column('density', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_materials', 'density')
    # ### end Alembic commands ###
