"""sub-material coefficients

Revision ID: d3b8bd4671a7
Revises: cdfe5116b5d4
Create Date: 2025-04-24 08:00:10.530222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3b8bd4671a7'
down_revision: Union[str, None] = 'cdfe5116b5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_material_coefficients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sub_material_id', sa.Integer(), nullable=False),
    sa.Column('thickness', sa.Integer(), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['sub_material_id'], ['sub_materials.id'], name=op.f('fk_sub_material_coefficients_sub_material_id_sub_materials')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sub_material_coefficients'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_material_coefficients')
    # ### end Alembic commands ###
