FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend /app/

# Set executable permissions
RUN chmod +x /app/entrypoints/entrypoint.sh

EXPOSE 8000

# ENTRYPOINT ["/app/entrypoints/entrypoint.sh"]