FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Set executable permissions
RUN chmod +x /app/entrypoints/entrypoint.sh

EXPOSE 8000

ENTRYPOINT ["/app/entrypoints/entrypoint.sh"]